export const SET_CONTENT = 'SET_CONTENT';
export const FETCHING_CONTENT = 'FETCHING_CONTENT';
export const GET_CONTENT_BY_CATEGORY = 'GET_CONTENT_BY_CATEGORY';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_CURRENT_DATA = 'SET_CURRENT_DATA';